name: iot_interface_with_aws_iot_core
description: A mobile app interface for IoT that talks to AWS IoT Core backend

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^4.0.0+1
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  freezed: ^2.3.2

flutter:

  uses-material-design: true
