name: iot_interface_with_aws_iot_core
description: A mobile super app interface for IoT's that talk to AWS IoT Core backend

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  hydrated_bloc: ^9.1.0
  mqtt_client: ^9.7.4
  dio: ^5.0.0
  flutter_dotenv: ^5.0.2
  sprintf: ^7.0.0
  typed_data: ^1.3.1
  bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  mockito: ^5.3.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - .env
