name: Run tests action

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

#      # Create certificates
#      - name: Create certificates
#        run: |
#          touch

      # Create .env file
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      # Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # Run tests
      - name: Run tests
        run: flutter test