name: Run tests action

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # Create certificates
      - name: Create certificates
        run: |
          cat assets/certificates/device_certificate.pem.crt.enc | openssl aes-256-cbc -d -pass pass:${{ secrets.CERTIFICATES_ENCRYPTION_PASSWORD }} > assets/certificates/device_certificate.pem.crt
          cat assets/certificates/private_key.pem.key.enc | openssl aes-256-cbc -d -pass pass:${{ secrets.CERTIFICATES_ENCRYPTION_PASSWORD }} > assets/certificates/private_key.pem.key
          cat assets/certificates/root_certificate_authority.pem.enc | openssl aes-256-cbc -d -pass pass:${{ secrets.CERTIFICATES_ENCRYPTION_PASSWORD }} > assets/certificates/root_certificate_authority.pem

      # Create .env file
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      # Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # Run tests
      - name: Run tests
        run: flutter test